# Generated by Django 5.2.2 on 2025-06-09 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='company',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='name',
            new_name='workshop_name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='certificate',
            field=models.FileField(default='', upload_to='certificates/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_no',
            field=models.CharField(default='0000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='location',
            field=models.CharField(default='nepal', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('make_year', models.IntegerField()),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('distance_traveled', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.servicetype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.servicetype')),
            ],
            options={
                'unique_together': {('customer', 'vendor', 'service')},
            },
        ),
    ]
